# These are the possible values for CMAKE_BUILD_TYPE:
IF(CMAKE_CONFIGURATION_TYPES)
    SET(CMAKE_CONFIGURATION_TYPES "Debug;Release;RelWithDebInfo;MinSizeRel" CACHE STRING "" FORCE)
ENDIF(CMAKE_CONFIGURATION_TYPES)

# As a matter of convenience, if the current binary dir ends with debug or dbg, create a Debug build.
GET_FILENAME_COMPONENT(CDIR "${CMAKE_CURRENT_BINARY_DIR}" NAME)
IF(CDIR STREQUAL "debug" OR CDIR STREQUAL "dbg")
SET(CMAKE_BUILD_TYPE "Debug")
ENDIF()

SET(ZENLANG_LIBRARIES)

# add debug definitions
 IF(CMAKE_COMPILER_IS_GNUCXX)
     ADD_DEFINITIONS( "-Wall" )
 ENDIF(CMAKE_COMPILER_IS_GNUCXX)

# add debug definitions
IF( CMAKE_BUILD_TYPE STREQUAL "Debug")
    ADD_DEFINITIONS( "-DDEBUG" )
ENDIF()

IF(WIN32)
    SET(lemon_cc "${ZEN_ROOT}/tools/lemon.exe")
    SET(re2c_cc "${ZEN_ROOT}/tools/re2c.exe")
ELSE(WIN32)
    SET(lemon_cc "${ZEN_ROOT}/tools/lemon")
    SET(re2c_cc "${ZEN_ROOT}/tools/re2c")
    SET(ZENLANG_LIBRARIES ${ZENLANG_LIBRARIES} pthread)
    SET(ZENLANG_LIBRARIES ${ZENLANG_LIBRARIES} dl)
ENDIF(WIN32)

IF(ZEN_GUI)
    ADD_DEFINITIONS( "-DGUI" )
    IF(WIN32)
        SET(ZENLANG_LIBRARIES ${ZENLANG_LIBRARIES} comctl32)
    ELSE(WIN32)
        SET(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${ZEN_ROOT}/tools")
        FIND_PACKAGE(GTK3 REQUIRED)
        INCLUDE_DIRECTORIES(${GTK3_INCLUDE_DIRS})
        SET(ZENLANG_LIBRARIES ${ZENLANG_LIBRARIES} ${GTK3_LIBRARIES})
    ENDIF(WIN32)
ENDIF()
